### ISSUE TITLE
Add minimal amount of donation in packages with type VARIABLE

### ISSUE THREAD

**Issue by AR7RIX** [FlorianSW/server-donation-tool#37]
Something like that minimalamount: '10.00'

```
- name: 'Perk #1'
    id: 2
    price:
      type: VARIABLE
      currency: EUR
      amount: '10.00'
      minimalamount: '10.00'
```
